// Command rest is the HTTP REST API entry point.
//
// Build-time Swagger annotations are processed by \`make swagger\` and the
// generated package is imported by the side-effecting blank import below.
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"

	"go.uber.org/zap"

	_ "github.com/zhanbinb/go-clean-arch_demo/docs/swagger" // generated by \`make swagger\`

	wire "github.com/zhanbinb/go-clean-arch_demo/cmd"
	httpserver "github.com/zhanbinb/go-clean-arch_demo/internal/interfaces/http"
	"github.com/zhanbinb/go-clean-arch_demo/pkg/server"
)

// @title           Go Clean Architecture Demo API
// @version         2.0
// @description     Lightweight DDD + Gin + GORM demo with JWT auth.
// @BasePath        /
// @securityDefinitions.apikey  BearerAuth
// @in              header
// @name            Authorization
// @description     Type "Bearer {token}".
func main() {
	env := os.Getenv("APP_ENV")
	log.Printf("APP_ENV: %s", env)
	deps, err := wire.New(context.Background(), env)
	if err != nil {
		log.Fatalf("init: %v", err)
	}
	defer func() { _ = deps.Log.Sync() }()

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	router := httpserver.NewRouter(
		deps.Cfg, deps.HTTPHandlers, deps.Log,
		deps.JWT, deps.Limiter, deps.PromReg,
	)

	httpSrv := server.NewHTTPServer(deps.Cfg.Server.HTTPAddr(), router, deps.Log.Zap())
	if err := httpSrv.Run(ctx); err != nil {
		deps.Log.Fatal("http server exited", zap.Error(err))
	}
	deps.Log.Info("rest server stopped")
}
