run:
  timeout: 5m
  tests: true
  skip-dirs:
    - api/gen
    - docs/swagger
    - tmp
    - bin

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
      - name: var-naming
      - name: error-strings
      - name: error-naming
      - name: error-return
      - name: if-return
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
  gosec:
    excludes:
      - G104  # unhandled errors - covered by errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
  max-same-issues: 0
